---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileSuperAdmin

mobile_app_groups:
  - mobileAdmin

portal_anonymous_register:
  - portalAnonymous

portal_loggedin_register:
  - portalLoggedin

mobile_device_groups:
  - appAccess
  - certificateAccess
  - contentAccess
  - courseAccess
  - deviceCreate
  - dialcodeAccess
  - locationAccess
  - orgAccess
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userUpdate
  - contentTempAccess
  - groupCreate
  - groupUpdate
  - groupAccess
  - groupAdmin
  - refreshTokenCreate
  - discussionAccess
  - anonymousCertificateAccess
  - anonymousContentAccess
  - anonymousCourseAccess
  - anonymousOrgAccess
  - anonymousUserAccess
  - anonymousAppAccess
  - anonymousUserCreate
  - readNotificationFeed
  - updateNotificationFeed
  - deleteNotificationFeed
  - cloudUrlsCreate
  - observationAccess
  - observationCreate
  - observationUpdate
  - programAccess
  - projectAccess
  - projectCreate
  - projectUpdate
  - registryAccess
  - solutionAccess
  - surveyAccess
  - surveyUpdate
  - frameworkAdmin
  - frameworkCreate
  - userSuperAdmin
  - orgUpdatecontent 
  - SuperAdmin
  - orgSuperAdmin
  - orgAdmin
  - dataAccess
  - dataCreate
  - contentAdmin
  - contentTempAccess
  - pluginAccess
  - channelAdmin
  - noteAccess
  - userTempAdmin

anonymous_user_groups:
  - deviceCreate
  - locationAccess
  - telemetryCreate
  - anonymousCertificateAccess
  - anonymousContentAccess
  - anonymousCourseAccess
  - anonymousOrgAccess
  - anonymousUserAccess
  - anonymousAppAccess
  - anonymousUserCreate

kong_all_consumer_groups:
  - announcementAccess
  - anonymousCertificateAccess
  - anonymousUserAccess
  - anonymousUserCreate
  - appAccess
  - appAdmin
  - appCreate
  - appUpdate
  - automatedReportAccess
  - badgeAccess
  - badgeAdmin
  - badgeCreate
  - badgeUpdate
  - certificateAccess
  - certificateAdmin
  - certificateCreate
  - certificateUpdate
  - channelAccess
  - channelAdmin
  - channelCreate
  - channelUpdate
  - cloudUrlsCreate
  - contentAccess
  - contentAdmin
  - contentCreate
  - contentSuperAdmin
  - contentTempAccess
  - contentUpdate
  - courseAccess
  - courseAdmin
  - courseCreate
  - courseUpdate
  - dataAccess
  - dataCreate
  - dbAccess
  - deleteNotificationFeed
  - deviceCreate
  - dialcodeAccess
  - dialcodeAdmin
  - dialcodeCreate
  - dialcodeUpdate
  - digiLockerAccess
  - discussionAccess
  - druidReportAdmin
  - druidReportCreate
  - externalCertificateAccess
  - frameworkAccess
  - frameworkAdmin
  - frameworkCreate
  - frameworkUpdate
  - group
  - groupAccess
  - groupAdmin
  - groupCreate
  - groupUpdate
  - locationAccess
  - mentorServiceMentee
  - mentorServiceMentor
  - mentorServiceOrgAdmin
  - mentorServiceSysAdmin
  - mlApp
  - mobileAdmin
  - mobileSuperAdmin
  - noteAccess
  - noteAdmin
  - noteCreate
  - noteUpdate
  - objectAccess
  - observationAccess
  - observationCreate
  - observationUpdate
  - orgAccess
  - orgAdmin
  - orgCreate
  - orgUpdate
  - orgSuperAdmin
  - orgUpdatecontent
  - pageAccess
  - pluginAccess
  - portalAnonymous
  - portalLoggedin
  - programAccess
  - programsAccess
  - programsUpdate
  - projectAccess
  - projectCreate
  - projectUpdate
  - readNotificationFeed
  - refreshTokenCreate
  - registryAccess
  - registryUpdate
  - reportsAccess
  - reportsAdmin
  - reportsCreate
  - reportsUpdate
  - solutionAccess
  - solutionsAccess
  - solutionsUpdate
  - ssoCreate
  - storageReportDownload
  - SuperAdmin
  - surveyAccess
  - surveyUpdate
  - telemetryCreate
  - updateNotificationFeed
  - useraccess
  - userAccess
  - userAdmin
  - userCreate
  - userSuperAccess
  - userSuperAdmin
  - userTempAdmin
  - userUpdate

kong_consumers:
  - username: api-admin
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: mobile_devicev2
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: portal_anonymous_register
    groups: "{{ portal_anonymous_register }}"
    state: present
  - username: portal_loggedin_register
    groups: "{{ portal_loggedin_register }}"
    state: present
  - username: portal_anonymous
    groups: "{{ anonymous_user_groups }}"
    state: present
 # - username: portal_loggedin
 #   groups: "{{ kong_all_consumer_groups }}"
 #   state: present
 # - username: portal_anonymous_fallback_token
 #   groups: "{{ anonymous_user_groups }}"
 #   state: present
 # - username: portal_loggedin_fallback_token
 #   groups: "{{ kong_all_consumer_groups }}"
 #   state: present
