- name: Create the directory
  file: path={{ mongo_backup_dir }} state=directory recurse=yes
  
- set_fact:
    mongo_backup_file_name: "mongo-backup-{{ ansible_hostname }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}"
 
- set_fact:
    mongo_backup_file_path: "{{ mongo_backup_dir }}/{{ mongo_backup_file_name }}"

- name: take dump
  shell: "mongodump --out={{ mongo_backup_file_path }}"
    
- name: Compress the backup file
  shell: "tar -czf {{ mongo_backup_file_path }}.tar.gz {{ mongo_backup_file_path }}"

- name: upload to gcs
  include_role:
    name: artifacts-upload-gcp
  vars:
    artifacts_container: "{{ backup_bucket }}/{{ mongo_backup_folder }}"
    artifact_path: "{{ mongo_backup_file_path }}.tar.gz"
    artifact: "{{ mongo_backup_file_name }}.tar.gz"
    service_account:  "{{ gcp_backups_service_account }}"
 
- name: clean up backup dir after upload
  file: path={{ mongo_backup_dir }} state=absent
