- name: Create the directory
  file: path={{ redis_backup_dir }} state=directory recurse=yes
  

- set_fact:
    redis_backup_file_name: "redis-backup-{{ lookup('pipe', 'date +%Y-%m-%d-%T') }}.rdb"
 
- set_fact:
    redis_backup_file_path: "{{ redis_backup_dir }}/{{ redis_backup_file_name }}"


- name: copy dump.rdb file
  copy:
    src: /home/learning/redis-stable/dump.rdb
    dest: "{{ redis_backup_dir }}/{{ redis_backup_file_name }}"
    remote_src: yes
    

- set_fact:
    redis_backup_name: "redis_backup_{{ lookup('pipe', 'date +%Z-%Y-%m-%d-%H-%M-%S') }}"
- name: upload to gcs
  include_role:
    name: artifacts-upload-gcp
  vars:
    artifacts_container: "{{ backup_bucket }}/{{ redis_backup_folder }}/{{redis_backup_name}}"
    artifact_path: "{{redis_backup_dir}}"
    artifact: "{{redis_backup_file_name}}"
    service_account: "{{ gcp_backups_service_account }}"

- name: clean up backup dir after upload
  file: path={{ redis_backup_dir }} state=absent

- name: Keyspace info
  shell: "echo info keyspace | ./src/redis-cli"
  register: restoreinfo
  args:
    chdir: "/home/learning/redis-stable/"

- debug: var=restoreinfo.stdout_lines

